stages:
  - check
  - build

format-job:
  stage: check
  image: clang-format:12
  script:
    - clang-check-last-commit

build-job:
  stage: build
  image: ubuntu:20.04-build
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
